name: guipilot
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - setuptools=71.0.4
  - wheel=0.43.0
  - ca-certificates=2024.8.30
  - openssl=3.3.2
  - numpy=1.26
  - pandas=2.2
  - scipy=1.13
  - scikit-learn=1.5
  - scikit-image=0.24
  - opencv=4.10
  - matplotlib=3.9
  - pillow=10.2
  - seaborn=0.13
  - networkx=3.3
  - sympy=1.13
  - shapely=2.0
  - python-dotenv=1.0
  - psutil=6.0
  - tqdm=4.66
  - typing-extensions=4.12
  - requests=2.32
  - urllib3=2.2

