name: guipilot-gpu
channels:
  - nvidia/label/cuda-12.0.0
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=24.0
  - setuptools=71.0.4
  - wheel=0.43.0
  - ca-certificates=2024.8.30
  - openssl=3.3.2
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.43
  - gcc=14.1.0
  - gcc_impl_linux-64=14.1.0
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libnvvm-samples=12.0.94
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - readline=8.2
  - sysroot_linux-64=2.12
  - tk=8.6.13
  - xz=5.2.6
  - numpy=1.26
  - pandas=2.2
  - scipy=1.13
  - scikit-learn=1.5
  - scikit-image=0.24
  - opencv=4.10
  - matplotlib=3.9
  - pillow=10.2
  - seaborn=0.13
  - networkx=3.3
  - sympy=1.13
  - shapely=2.0
  - python-dotenv=1.0
  - psutil=6.0
  - tqdm=4.66
  - typing-extensions=4.12
  - requests=2.32
  - urllib3=2.2

